version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - epub
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build: # prepare Doxyfile, run Doxygen, prepare Sphinx
      - sed s/@DOXYGEN_INPUT_DIR@/../g\;s/@DOXYGEN_OUTPUT_DIR@/_doxygen/g\;s/@DOXYGEN_DOT_PATH@/$(which dot)/g docs/Doxyfile.in > docs/Doxyfile
      - cat docs/Doxyfile
      - cd docs && doxygen
      - mkdir -p docs/extra/doxygen
      - cp -r docs/_doxygen/html/* docs/extra/doxygen
      - cp docs/conf.py.in docs/conf.py

conda:
  environment: docs/environment.yml
