version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - epub
  - pdf

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - cp docs/source/conf.py.in docs/source/conf.py

python:
   install:
     - requirements: docs/requirements.txt
