version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - epub
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_install:
      - cp docs/source/conf.py.in docs/source/conf.py
    post_build:
      - cp -r docs/build/html docs/source/_build/html/doxygen

conda:
  environment: docs/environment.yml
