name: remage-docs

channels:
  - conda-forge
  - default

dependencies:
  - python=3.10
  - doxygen
  - breathe
  - exhale
  - furo
  - myst-parser
  - setuptools-scm
  - sphinx
  - sphinx-copybutton
  - sphinx-inline-tabs
