name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
    paths-ignore:
      - '**.md'
  pull_request:
  release:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test_on_linux:
    name: Test on Linux containers (Ubuntu LTS)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container_version:
        - G4.11.0
        - slim

    container: docker://gipert/remage-base:${{ matrix.container_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make
        make install
        make test

# vim: expandtab tabstop=2 shiftwidth=2
