name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:

  in_legend_container:
    name: Test in LEGEND container (CentOS)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container_version:
        - latest
        # - ...

    container: docker://legendexp/legend-base:${{ matrix.container_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: .github/workflows/build.sh

  on_macos:
    name: Test on macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      run: brew install --force-bottle root geant4
    - name: Build project
      run: .github/workflows/build.sh

# vim: expandtab tabstop=2 shiftwidth=2
